"""Write the Windows version resource PyInstaller embeds in the .exe.

Without `--version-file`, PyInstaller produces an exe with NO version resource:
right-click -> Properties -> Details is blank, every release looks identical to
Windows, and the only thing telling two builds apart is the filename — which is
deliberately constant (`ExileBot2PickitGenerator.exe`, the in-app updater's
download URL depends on it). So an updated copy looked like the old one.

Generated from version.py at build time, so the number in the exe's properties
can never drift from the release it was built at.

    python tools/make_version_file.py [output_path]     # default: build/version_info.txt
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "src" / "exilebot_pickit" / "version.py"

TEMPLATE = """# Auto-generated by tools/make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({maj}, {min}, {pat}, 0),
    prodvers=({maj}, {min}, {pat}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'c4Luffy'),
         StringStruct('FileDescription', 'Exiled Bot Pickit Generator'),
         StringStruct('FileVersion', '{ver}'),
         StringStruct('InternalName', 'ExileBot2PickitGenerator'),
         StringStruct('LegalCopyright', 'Community project. Not affiliated with '
                      'Grinding Gear Games, Path of Exile, Exiled Bot or poe.ninja.'),
         StringStruct('OriginalFilename', 'ExileBot2PickitGenerator.exe'),
         StringStruct('ProductName', 'Exiled Bot Pickit Generator'),
         StringStruct('ProductVersion', '{ver}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version() -> str:
    src = VERSION_FILE.read_text(encoding="utf-8")
    m = re.search(r'(?m)^VERSION\s*=\s*["\']([^"\']+)["\']', src)
    if not m:
        raise SystemExit(f"no VERSION found in {VERSION_FILE}")
    return m.group(1)


def main() -> int:
    version = read_version()
    parts = version.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise SystemExit(f"VERSION must be X.Y.Z, got {version!r}")
    maj, minor, pat = (int(p) for p in parts)

    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "build" / "version_info.txt"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(maj=maj, min=minor, pat=pat, ver=version),
                   encoding="utf-8", newline="\n")
    print(f"version resource for {version} -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
